---
- name: EPEL install
  hosts: localhost
 #  roles:
 #    - { role: geerlingguy.repo-epel, when: ansible_os_family == 'RedHat' }
  roles:
    - role: geerlingguy.repo-epel
      when: (ansible_facts['distribution'] == 'RedHat') or
            (ansible_facts['distribution'] == 'Rocky')
  become: true
  tags: epel

- name: Powerline dependencies
  hosts: localhost
  tasks:
    - name: Installing Dependencies
      ansible.builtin.yum:
        name: "{{ item }}"
        update_cache: true
        state: present
      with_items:
        - python3-pip
        - git
        - powerline
        - powerline-fonts
        - vim-ansible
      become: true

    - name: Create .bashrc, .vimrc, and .screenrc
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        mode: u=rwx
        force: true
        backup: true
      loop:
        - { src: 'templates/bashrc.j2', dest: '{{ ansible_env.HOME }}/.bashrc' }
        - { src: 'templates/vimrc.j2', dest: '{{ ansible_env.HOME }}/.vimrc' }
        - { src: 'templates/screenrc.j2', dest: '{{ ansible_env.HOME }}/.screenrc' }
      tags: dotfiles
