---
collections:
  - name: community.general
    source: https://galaxy.ansible.com

roles:
  - name: geerlingguy.repo-epel
    source: https://galaxy.ansible.com

#  - name: powerline
#    source: https://github.com/bcdonadio/ansible-powerline/archive/master.tar.gz
