---
- name: Configure Powerline
  hosts: localhost
  vars:
    vimcolorscheme: slate
  tasks:
    - name: Create .bashrc, .vimrc, and .screenrc
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        mode: u=rwx
        force: true
        backup: true
      loop:
        - { src: 'templates/bashrc.j2', dest: '{{ ansible_env.HOME }}/.bashrc' }
        - { src: 'templates/vimrc.j2', dest: '{{ ansible_env.HOME }}/.vimrc' }
        - { src: 'templates/screenrc.j2', dest: '{{ ansible_env.HOME }}/.screenrc' }
      tags: dotfiles
